FROM python:3.10.5

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the required packages within a virtual environment
RUN python -m venv env && \
    . env/bin/activate && \
    pip install -r requirements.txt

# Copy the rest of the application code
COPY . .

# Set the entrypoint
ENTRYPOINT ["python", "app.py"]
